# ---------------------- #
#      Site Configs      #
# ---------------------- #

title: Xue's Notes
url: http://notes.xmf.lu
permalink: /:categories/:title.html
paginate: 10
paginate_path: /page/:num


# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: false
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
timezone: China/Beijing


# ---------------------- #
#      Compile Sass      #
# ---------------------- #

# run `compass help compile` in terminal to find more available options
# compile:
#   no_line_comments: true
#   sass_dir: _sass
#   # css_dir: stylesheets
#   output_style: compressed

sass:
  sass_dir: _sass
  # fonts_dir: fonts
  debug_info: true
  output_style: compressed


# ---------------------- #
#       Deployment       #
# ---------------------- #

deploy:
  repository: git@github.com:xuemengfei/notes.xmf.lu.git
  branch: master


# ---------------------- #
#       Deployment       #
# ---------------------- #

navigation:
- text: Home
  url: /index.html
- text: Uncategorized
  url: /uncategorized/
- text: Test
  url: /test/
- text: about
  url: /about.html

# ---------------------- #
#    Social Networks     #
# ---------------------- #

# weibo:
#   username:
#   uid:
#   appkey:

# disqus:
